#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:2 todo:t |:t
#+TITLE: Scripts and configs to support tiling window managers including EXWM
#+DATE: <2020-11-21 Sat>
#+AUTHOR: Greg Grubbs
#+EMAIL: gregory@dynapse.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 28.0.50 with nativecomp
#+setupfile: ~/projects/emacs/org-html-themes/org/theme-readtheorg.setup
#+PROPERTY: header-args:emacs-lisp :results none
#+PROPERTY: header-args:bash :results none :shebang #!/usr/bin/env bash :tangle no
* Overview

  Minimalistic desktop environment things that are closely tied with my EXWM configuration
  and/or include some emacs lisp will be found in [[file:README.org][README.org]]

  This file handles creating all the basics for a DYI Linux desktop environment.  If you
  forego the pre-packaged desktop environments such as Gnome, KDE, XFCE, Mate, etc. you
  will need to substitute some of the conveniences those environments offer.

  Things like a panel, system tray, media controls, and so forth.

  The configuration below is very much geared to tiling window managers - I use EXWM, but
  much of the config and helper applications would be useful with i3, StumpWM and others.

  Tangle this file to generate shell scripts.

* Control scripts

** Volume
   Volume control uses the =pulseaudio-control= script

   To simplify invocation of the command, create a wrapper script per machine with all
   the parameters filled in.

   Here's the wrapper for GladOS, my Dell XPS 13" 2-in-1 laptop
   #+begin_src bash :tangle ~/bin/pulseaudio-control-glados
     # The arguments for this script:
     if [ -z "$1" ]; then
         echo "\
     Usage: $0 [output, up, down, mute, unmute, togmute, next-sink, sync]"
         exit 0
     fi
     ~/bin/pulseaudio-control \
         --icons-volume " , " \
         --icon-muted " " \
         --sink-nicknames-from "device.description" \
         --sink-nickname "alsa_output.pci-0000_00_1f.3.analog-stereo:  Speakers" \
         --sink-nickname "bluez_sink.38_18_4C_3E_36_51.a2dp_sink:  Headphones" \
         --sink-nickname "bluez_sink.BC_F2_92_A7_29_EC.a2dp_sink: Earpiece" \
         $1
   #+end_src
* OS Applications
  The shell scripts here expect certain applications to be installed, so let's take care
  of those
** Guix
  GNU Guix changes everything - packages will be added declaratively
** Ubuntu
   #+begin_src bash
     # Add repo for Albert - Ubuntu 21.10
     curl https://build.opensuse.org/projects/home:manuelschneid3r/public_key | sudo apt-key add -
     echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_21.10/ /' | sudo tee /etc/apt/sources.list.d/home:manuelschneid3r.list
     sudo wget -nv https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_21.10/Release.key -O "/etc/apt/trusted.gpg.d/home:manuelschneid3r.asc"
     sudo apt update
     sudo apt install albert

     sudo apt update
     sudo apt -y install \
          albert \
          autorandr \
          blueman \
          compton \
          cowsay \
          discount \
          feh \
          fonts-hack \
          fonts-opensymbol \
          fonts-cantarell \
          fonts-material-design-icons-iconfont \
          fonts-firacode \
          fortune-mod \
          gcc \
          git \
          gwenview \
          ipython3 \
          jupyter \
          libgccjit-9-dev \
          libreoffice-gtk3 \
          mlocate \
          pdsh \
          policykit-1-gnome \
          ruby \
          silversearcher-ag \
          slick-greeter \
          tree \
          vlc \
          wmctrl \
          xdotool \
          xfce4-mount-plugin \
          xfce4-panel \
          xfce4-power-manager-plugins \
          xfce4-pulseaudio-plugin \
          xfce4-screenshooter \
          xfce4-statusnotifier-plugin \
          xfce4-whiskermenu-plugin \
          xfconf \
          xscreensaver

   #+end_src
** X Session Desktop file
   Having this allows EXWM to be chosen from the Display Manager

   Place in =/usr/share/xsessions/emacs.desktop=
   #+begin_src conf :tangle /sudo::/usr/share/xsessions/emacs.desktop
     [Desktop Entry]
     Encoding=UTF-8
     Type=XSession
     Name=Emacs EXWM Session
     GenericName=Window Manager
     Icon=emacs
     Exec=/usr/local/bin/emacs
     NoDisplay=false
     Hidden=false
     Categories=Application;System;
     StartupNotify=false
     X-GNOME-Autostart-Notify=false
     X-GNOME-Autostart-Phase=WindowManager
     X-GNOME-Provides=windowmanager
     X-GNOME-WMName=EXWM
     DesktopNames=EXWM
     X-LightDM-DesktopName=exwm

     [Window Manager]
     Name=exwm
     SessionManaged=true
     StartupNotification=false
   #+end_src

   Install the above as an X Session alternative
   #+begin_src bash
     sudo update-alternatives --install /usr/share/xsessions/default.desktop default-xsession.desktop /usr/share/xsessions/emacs.desktop 20
   #+end_src
** Lightdm fancy icon for Emacs window manager
   This is for use with LightDM Slick Greeter - look for a =badges= directory for
   whichever DM you use
   #+begin_src bash
     sudo cp -v ~/emacs/pixmaps/emacs-icon-22x22.png /usr/share/slick-greeter/badges/emacs.png
   #+end_src
** Touchpad and external mouse settings
   These configs set up my preference for scrolling direction with the touchpad and an
   external mouse.

   #+begin_src conf :tangle /sudo::/usr/share/X11/xorg.conf.d/41-gregor-libinput.conf
     # Control scrolling direction and tap to click - Add this to libinput touchpad config in  =/etc/X11/xorg.conf.d/40-libinput.conf=
     Section "InputClass"
             Identifier "libinput touchpad gorto"
             MatchIsTouchpad "on"
             MatchDevicePath "/dev/input/event*"
             Option "NaturalScrolling" "on"
             Option "Tapping" "on"
             Option "ClickMethod" "clickfinger"
     EndSection
     Section "InputClass"
             Identifier "libinput pointer gorto"
             MatchIsPointer "on"
             MatchDevicePath "/dev/input/event*"
             Driver "libinput"
             Option "NaturalScrolling" "off"
             Option "AccelSpeed" "0.3"
     EndSection
   #+end_src

* Useful shell when no DE is available
** Script to run autostart apps including compositor
  I run a shell script which starts up key helper apps like albert/ulauncher, picom/compton and
  xscreensaver.  Also some common mouse and keyboard settings that are ordinarily handled
  in the DE.

  NOTE: If both =xscreensaver= and =xfce4-screensaver= are running, they can "fight" for
  control in the Lightdm screen and prevent any user input!  So for now I will just use
   =xfce4-screensaver=

  #+begin_src bash :tangle ~/bin/dns-restarter.sh
    sudo systemctl restart systemd-resolved.service
  #+end_src
  #+begin_src bash :tangle ~/bin/capsctrl.sh
    # Set CAPS LOCK as control
    setxkbmap -verbose  -option "ctrl:nocaps"
    # To re-enable caps lock
    # setxkbmap -option
  #+end_src
  #+begin_src bash :tangle ~/bin/numlockon.sh
    numlockx on
  #+end_src
  #+begin_src bash :tangle ~/bin/emacswm.sh
    echo "Running emacswm.sh script from `pwd`"
    # Set CAPS LOCK key as CTRL
    ~/bin/capsctrl.sh
    ~/bin/numlockon.sh
    # Network Manager using CLI
    # ref https://core.docs.ubuntu.com/en/stacks/network/network-manager/docs/configure-wifi-connections
    # If you get 'secrets were required' when trying to connect, delete the connection first
    # sudo nmcli d wifi   # to scan wifi
    # nmcli connection delete moodseer-5G
    # nmcli d wifi connect moodseer-5G password blah

    # run an authentication agent for graphical programs that need SUDO - like GParted
    if [ -x "/usr/lib/polkit-gnome-authentication-agent-1" ] ; then
        (cd /tmp && nohup /usr/lib/polkit-gnome-authentication-agent-1&)
    elif [ -x "/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1" ] ; then
        (cd /tmp && nohup /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1&)
    fi


    # Set scrolling direction to "natural"
    xmodmap -e "pointer = 1 2 3 4 5"

    rm -vf nohup.out
    echo Start compositor
    if which picom ; then
        nohup picom &
    elif which compton ; then
        nohup compton &
    fi

    echo Start notification system
    nohup dunst&


    echo Start albert
    nohup albert &
    nohup nm-applet&
    # echo Remember iflipb for changing buffers - and/or buffer-expose-mode
    # xrandr --output eDP-1 --brightness .8

    # echo Start xscreensaver
    # xscreensaver &
    nohup xfce4-power-manager&
  #+end_src
** Scripts to rotate wallpaper on multiple screens
   The schedule script runs only if it is not already running
   #+begin_src bash :tangle ~/bin/rotate-wallpapers.sh
     # # Get active monitors
     # IFS=$'\n'
     # for monitor in `xrandr --listactivemonitors| egrep '^ *[0-9]'`
     # do
     #     cleaned=`echo $monitor | sed -E 's/^ *([0-9]+): [\+\*]+([-0-9a-zA-Z]+) ([0-9]+)[^x]*x([0-9]+).+/\1 \2 \3x\4/'`
     #     # echo $cleaned
     #     IFS=' ' read mon name res <<< ${cleaned}
     #     echo "Monitor #${mon} named ${name} has resolution ${res}"
     #     # naiively assume correct dir exists
     #     DISPLAY=:0 /usr/bin/feh --xinerama-index ${mon} --bg-max --randomize ~/backgrounds/safe/${res}/
     # done

     # DISPLAY=:0.0 /usr/bin/feh --xinerama-index 1 --bg-max --randomize ~/backgrounds/safe/1920x1200/
     # DISPLAY=:0.0 /usr/bin/feh --xinerama-index 0 --bg-max --randomize ~/backgrounds/safe/3440x1440/

     feh --bg-fill --randomize --recursive  ~/backgrounds/safe/
   #+end_src
   #+begin_src bash :tangle ~/bin/schedule-rotate-wallpapers.sh
     #!/usr/bin/env bash
     # check for running process
     pids=$(/bin/pgrep -f schedule-rotate-wallpapers )
     for pid in $pids ; do
         if [ $pid != $$ ] ; then
             echo "already running"
             exit 0
         fi
     done

     while true
     do
         # DISPLAY=:0.0 /usr/bin/feh --bg-max --randomize ~/backgrounds/safe/1920x1200/
         /home/gregj/bin/rotate-wallpapers.sh
         sleep 1200
     done
   #+end_src
** Script to launch panel with good widgets
   #+begin_src bash :tangle ~/bin/xfce-panel-widgets.sh
     nohup xfce4-panel &
     # Clipboard manager
     # nohup parcellite &
     # Network Manager applet
     nohup nm-applet --indicator &
     # Bluetooth setup + file transfer
     nohup /usr/bin/python3 /usr/bin/blueman-applet &
     # # Printer notifications - this applet was causing problems with EXWM - somehow added an unseen dedicated window
     # nohup /usr/bin/python3 /usr/share/system-config-printer/applet.py &
   #+end_src
** Script to toggle autohiding of xfce4-panel
   #+begin_src bash :tangle ~/bin/toggle-xfce4-panel-hide.sh
     #!/bin/bash

     ##### EDIT these values to suit
     # the panel to affect
     PANEL=1

     # the hide behaviour setting (1=intelligently, 2=always)
     HIDE=2

     ##### Don't edit anything below
     # get the current setting
     CURR=$(xfconf-query -c xfce4-panel -p /panels/panel-$PANEL/autohide-behavior)

     xfconf-query -c xfce4-panel -p /panels/panel-$PANEL/disable-struts -s false
     # show hidden or hide displayed
     case $CURR in
             #currently visible, so hide it
         0) xfconf-query -c xfce4-panel -p /panels/panel-$PANEL/autohide-behavior -s $HIDE ;;
             # currently intelligent, set to visible
         1) xfconf-query -c xfce4-panel -p /panels/panel-$PANEL/autohide-behavior -s 0 ;;
             # currently always hidden, set to visible
         2) xfconf-query -c xfce4-panel -p /panels/panel-$PANEL/autohide-behavior -s 0 ;;
             # otherwise ignore
         ,*) ;;
     esac

   #+end_src



** Script to adjust screen brightness
   #+begin_src bash :tangle ~/bin/gjg-bright.sh
     #!/usr/bin/env bash

     # base dir for backlight class
     basedir="/sys/class/backlight/"

     # get the backlight handler
     handler=$basedir$(ls $basedir)"/"

     # get current brightness
     old_brightness=$(cat $handler"brightness")

     # get max brightness
     max_brightness=$(cat $handler"max_brightness")

     # get current brightness %
     old_brightness_p=$(( 100 * $old_brightness / $max_brightness ))

     # calculate new brightness %
     new_brightness_p=$(($old_brightness_p $1))

     # calculate new brightness value
     new_brightness=$(( $max_brightness * $new_brightness_p / 100 ))

     # set the new brightness value
     sudo chmod 666 $handler"brightness"
     echo $new_brightness > $handler"brightness"

   #+end_src
* Autorandr setup
  The config to start with is set up using =autorandr --save <profile>= with and without
  monitors attached.  I create =laptop-only=, =dual-monitor= and =monitor-only= profiles

  The resulting config files are stored in =~/.config/autorandr/=

  In addition, there are =postswitch= scripts that run whenever a profile is activated.
  Set to right-handed mouse in laptop-only for the trackpad, left-handed for external
  mouse when using external monitor.

  #+begin_src bash
    mkdir -p ~/.config/autorandr/laptop-only ~/.config/autorandr/dual-monitor ~/.config/autorandr/monitor-only
  #+end_src

** Laptop-only
   #+begin_src bash :tangle ~/.config/autorandr/laptop-only/postswitch
     #!/usr/bin/env bash
     /home/gregj/bin/righty
     /home/gregj/bin/capsctrl.sh
     /home/gregj/bin/schedule-rotate-wallpapers.sh
   #+end_src
** Dual-monitor
   #+begin_src bash :tangle ~/.config/autorandr/dual-monitor/postswitch
     #!/usr/bin/env bash
     /home/gregj/bin/lefty
     /home/gregj/bin/capsctrl.sh
     /home/gregj/bin/schedule-rotate-wallpapers.sh
   #+end_src
** Monitor-only
   #+begin_src bash :tangle ~/.config/autorandr/monitor-only/postswitch
     #!/usr/bin/env bash
     /home/gregj/bin/lefty
     /home/gregj/bin/capsctrl.sh
     /home/gregj/bin/schedule-rotate-wallpapers.sh
   #+end_src
* Desktop files to use with Albert / ulauncher / rofi
** Assure directories are created before tangling
   #+begin_src bash
     mkdir -p ~/.local/share/applications ~/.local/share/pixmaps/
     sudo update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/firefox 50
   #+end_src
** Images referred to in the files below
   These images are to be placed in =~/.local/share/pixmaps/=

   Copy all images from the [[file:~/projects/emacs/emacs-gregoryg/emacs/pixmaps/][~/emacs/pixmaps]] directory
   #+begin_src bash :results none
     rsync -av ~/emacs/pixmaps/ ~/.local/share/pixmaps/
   #+end_src
** Amazon.com
   #+begin_src conf :tangle ~/.local/share/applications/amazon.desktop
     [Desktop Entry]
     Name=Amazon.com
     Comment=That's right
     Exec=xdg-open https://www.amazon.com/
     Icon=/home/gregj/.local/share/pixmaps/amazon-logo-rgb.png
     Terminal=false
     Type=Application
     Categories=Shopping;Retail;
   #+end_src
** Browser
   + generic browser, specified by update-alternatives x-www-browser *or* xdg-settings
   #+begin_src conf :tangle ~/.local/share/applications/browser-generic.desktop
     [Desktop Entry]
     Name=Browser
     Comment=The default web browser
     Exec=xdg-open https://google.com
     Icon=/home/gregj/.local/share/pixmaps/browser-generic.png
     Terminal=false
     Type=Application
     Categories=Fun;Web
   #+end_src
** Capsctrl
   #+begin_src conf :tangle ~/.local/share/applications/capsctrl.desktop
     [Desktop Entry]
     Name=Capsctrl
     Comment=Use CAPS LOCK as control
     Exec=/home/gregj/bin/capsctrl.sh
     Icon= /home/gregj/.local/share/pixmaps/CAPSoff.gif
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src
** Chrome
   Use this if you are not using the OS package manager or Flatpak installation - set
   =:tangle no= if you are
   #+begin_src conf :tangle no
     # ~/.local/share/applications/chrome.desktop
     [Desktop Entry]
     Encoding=UTF-8
     Name=Google Chrome
     GenericName=Web Browser
     Comment=Browse the Web
     Exec=flatpak run com.google.Chrome
     Icon= /home/gregj/.local/share/pixmaps/google-cloud-logo.png
     Terminal=false
     Type=Application
     Categories=Application;Network;WebBrowser;
     MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;
     StartupNotify=True
   #+end_src
** Cloudflare
   #+begin_src conf :tangle ~/.local/share/applications/cloudflare.desktop
     [Desktop Entry]
     Name=Cloudflare
     Comment=
     Exec=xdg-open https://cloudflare.com
     Icon= /home/gregj/.local/share/pixmaps/cloudflare-icon.png
     Terminal=false
     Type=Application
     Categories=Storage
   #+end_src

** Dired
   #+begin_src conf :tangle ~/.local/share/applications/emacs-dired.desktop
     # Stolen from https://emacs.stackexchange.com/a/16394/418
     [Desktop Entry]
        Encoding=UTF-8
        Version=1.0
        Type=Application
        NoDisplay=true
        Exec=emacsclient --no-wait --eval '(dired "%f")'
        Name=Dired
        Comment=Use Emacs Dired as file manager for OS
        Icon= /home/gregj/.local/share/pixmaps/rotate-wallpapers.jpg
        # Terminal=false
        Categories=Office;Productivity;Coolness
   #+end_src
** Discord
   #+begin_src conf :tangle no
 ~/.local/share/applications/discord.desktop
     [Desktop Entry]
     Encoding=UTF-8
     Name=Discord
     Comment=Communicate
     Exec=flatpak run com.discordapp.Discord
     Icon= /home/gregj/.local/share/pixmaps/discord.png
     Terminal=false
     Type=Application
     Categories=Messaging
   #+end_src
** DNS Restarter
   #+begin_src conf :tangle ~/.local/share/applications/dns-restarter.desktop
     [Desktop Entry]
     Name=DNS Restarter
     Comment=Restart resolver service on stupid Ubuntu
     Exec=/home/gregj/bin/dns-restarter.sh
     Icon= /home/gregj/.local/share/pixmaps/ignition-sources-matches-icon.png
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src
** emacsclient
   #+begin_src conf :tangle ~/.local/share/applications/userapp-emacsclient-6OAMT0.desktop
     [Desktop Entry]
     Encoding=UTF-8
     Version=1.0
     Type=Application
     NoDisplay=true
     Exec=/usr/local/bin/emacsclient --no-wait %f
     Name=emacsclient
     Comment=Custom definition for emacsclient
   #+end_src
** Erebor Synology
   #+begin_src conf :tangle ~/.local/share/applications/erebor.desktop
     [Desktop Entry]
     Name=Erebor Synology DSM
     Comment=Erebor
     Exec=xdg-open https://erebor.magichome:5001
     Icon= /home/gregj/.local/share/pixmaps/synology.png
     Terminal=false
     Type=Application
     Categories=Storage
   #+end_src
** Firefox
   Use this if you are not using the OS package manager installation - set =:tangle no= if
   you are
   #+begin_src conf :tangle no
     # ~/.local/share/applications/firefox.desktop
     [Desktop Entry]
     Encoding=UTF-8
     Name=Mozilla Firefox
     GenericName=Web Browser
     Comment=Browse the Web
     Exec=firefox
     Icon= /home/gregj/.local/share/pixmaps/firefox-128.png
     Terminal=false
     Type=Application
     Categories=Application;Network;WebBrowser;
     MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;
     StartupNotify=True
   #+end_src
** GitHub
   #+begin_src bash  :tangle ~/.local/share/applications/github.desktop
     [Desktop Entry]
     Name=GitHub
     Comment=GitHub
     Exec=xdg-open https://github.com/gregoryg/
     Icon= /home/gregj/.local/share/pixmaps/github4.jpg
     Terminal=false
     Type=Application
     Categories=Office;Calendar;
   #+end_src
** Google Cloud Platform
   #+begin_src bash  :tangle ~/.local/share/applications/gcp.desktop
     [Desktop Entry]
     Name=GCP Google Cloud
     Comment=GCP
     Exec=xdg-open https://console.cloud.google.com/compute/instances?authuser=0
     Icon= /home/gregj/.local/share/pixmaps/google-cloud-logo.png
     Terminal=false
     Type=Application
     Categories=Cloud;Virtualization
   #+end_src

** Google Maps
   #+begin_src bash  :tangle ~/.local/share/applications/google-maps.desktop
     [Desktop Entry]
     Name=Google Maps
     Comment=
     Exec=xdg-open https://maps.google.com?authuser=1
     Icon= /home/gregj/.local/share/pixmaps/Maps_Pin_FullColor.max-1000x1000.png
     Terminal=false
     Type=Application
     Categories=Maps;Navigation
   #+end_src
** GoToWebinar
   GoToWebinar does not support Firefox in 2020
   Therefore this shortcut uses Chrome
   #+begin_src conf :tangle ~/.local/share/applications/gotowebinar.desktop
     [Desktop Entry]
     Name=GoToWebinar
     Comment=Launched in Chrome
     Exec=google-chrome https://app.gotowebinar.com/unified/index.html#/
     Icon= /home/gregj/.local/share/pixmaps/gotowebinar.png
     Terminal=false
     Type=Application
     Categories=InstantMessaging;
   #+end_src
** Hangouts / Google Chat
   #+begin_src conf :tangle ~/.local/share/applications/fhangouts.desktop
     [Desktop Entry]
     Name=Chat (nee Hangouts)
     Comment=Google Chat
     Exec=xdg-open https://mail.google.com/chat/u/1
     Icon=/home/gregj/.local/share/pixmaps/google-chat.png
     Terminal=false
     Type=Application
     Categories=InstantMessaging;
   #+end_src
** Harvester VIRTUALIZATION BABAY
   #+begin_src conf :tangle ~/.local/share/applications/harvester.desktop
     [Desktop Entry]
     Name=Harvester Awesomeness
     Comment=Why, k8s virtualization of course
     Exec=xdg-open https://protomolecule.magichome:30443
     Icon= /home/gregj/.local/share/pixmaps/harvester-icon-text.png
     Terminal=false
     Type=Application
     Categories=Office;Productivity
   #+end_src
** HBO Max
   #+begin_src conf :tangle ~/.local/share/applications/hbomax.desktop
     [Desktop Entry]
     Name=HBO Max
     Comment=HBO Max in Browser
     Exec=xdg-open https://play.hbomax.com/
     Icon=/home/gregj/.local/share/pixmaps/hbomax.png
     Terminal=false
     Type=Application
     Categories=Entertainment;
   #+end_src
** Home Assistant
   #+begin_src conf :tangle ~/.local/share/applications/home-assistant.desktop
     [Desktop Entry]
     Name=Home Assistant
     Comment=Home Assistant of 2 Moonz
     Exec=xdg-open http://erebor.magichome:8123/
     Icon= /home/gregj/.local/share/pixmaps/homeassistant.png
     Terminal=false
     Type=Application
     Categories=Automation;
   #+end_src
** IntelliJ IDEA Community Edition
   #+begin_src conf :tangle ~/.local/share/applications/jetbrains-idea-ce.desktop
     [Desktop Entry]
     Version=1.0
     Type=Application
     Name=IntelliJ IDEA Community Edition
     Icon=/home/gregj/Downloads/idea-IC-202.6397.94/bin/idea.svg
     Exec="/home/gregj/Downloads/idea-IC-202.6397.94/bin/idea.sh" %f
     Comment=Capable and Ergonomic IDE for JVM
     Categories=Development;IDE;
     Terminal=false
     StartupWMClass=jetbrains-idea-ce
   #+end_src

** JMeter
   #+begin_src conf :tangle ~/.local/share/applications/jmeter.desktop
     [Desktop Entry]
     Version=1.0
     Type=Application
     Name=JMeter
     Icon= /home/gregj/.local/share/pixmaps/jmeter-feather.png
     Exec="/home/gregj/bin/apache-jmeter-5.4.3/bin/jmeter"
     Comment=Load testing
     Categories=Development;Metrics;Testing;
     Terminal=false
   #+end_src
** Jupyter Lab - local server
   + tangle startup script
     #+begin_src bash :tangle ~/bin/start_jupyterlab.sh
       # Requires c.ServerApp.allow_remote_access = True in ~/.jupyter/jupyter_lab_config.py
       # Set password with `jupyter-lab password` ; stored in ~/.jupyter/jupyter_server_config.json
       jupyter-lab --no-browser --ip=jupyter.127.0.0.1.nip.io --port=8442
       # jupyter-lab --ip=jupyter.127.0.0.1.nip.io --port=8442
     #+end_src
   + Tangle the desktop file
   #+begin_src conf :tangle ~/.local/share/applications/jupyter-lab.desktop
     [Desktop Entry]
     Name=Jupyter Lab
     Comment=Browse local Jupyter Lab server
     Exec=xdg-open http://jupyter.127.0.0.1.nip.io:8442
     Icon= /home/gregj/.local/share/pixmaps/1200px-Jupyter_logo.svg.png
     Terminal=false
     Type=Application
     Categories=Automation;
   #+end_src

** Lefty Loosey
   #+begin_src conf :tangle ~/.local/share/applications/lefty.desktop
     [Desktop Entry]
     Name=Lefty Loosey
     Comment=Set attached mouse to left-handed use
     Exec=/home/gregj/bin/lefty
     Icon= /home/gregj/.local/share/pixmaps/lefthand_logo.gif
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src

** LinkedIn
   #+begin_src conf :tangle ~/.local/share/applications/linkedin.desktop
     [Desktop Entry]
     Name=LinkedIn
     Comment=Networking
     Exec=xdg-open https://linkedin.com/
     Icon=/home/gregj/.local/share/pixmaps/linkedin-glossy.jpg
     Terminal=false
     Type=Application
     Categories=Office;Networking;Social
   #+end_src
** Google Calendar
   #+begin_src conf :tangle ~/.local/share/applications/gcalendar.desktop
     [Desktop Entry]
     Name=Google Calendar
     Comment=Google Calendar in Browser
     Exec=xdg-open https://calendar.google.com/calendar/u/0/
     Icon=/home/gregj/.local/share/pixmaps/google-calendar-icon.png
     Terminal=false
     Type=Application
     Categories=Office;Calendar;
   #+end_src
** Google Gmail
   #+begin_src conf :tangle ~/.local/share/applications/gmail.desktop
     [Desktop Entry]
     Name=Gmail Corporate Mail
     Comment=Google EMail in Browser
     Exec=xdg-open https://mail.google.com/mail/u/0/#search/in:inbox+is:unread
     Icon= /home/gregj/.local/share/pixmaps/gmail-logo.png
     Terminal=false
     Type=Application
     Categories=Office;Mail;
   #+end_src
** Microsoft Teams
   As of [2021-01-26 Tue] I am having microphone problems using the Linux client for
   Teams.  Things seem to run fine in the browser, however.
   #+begin_src conf :tangle ~/.local/share/applications/teams-browser.desktop
     [Desktop Entry]
     Name=Microsoft Teams in browser
     Comment=
     Exec=xdg-open https://teams.microsoft.com
     Icon=/home/gregj/.local/share/pixmaps/teams-logo.png
     Terminal=false
     Type=Application
     Categories=InstantMessaging;
   #+end_src
** Monitor change
   Run when external monitor is connected/disconnected
   #+begin_src conf :tangle ~/.local/share/applications/autorandr-monitor.desktop
     [Desktop Entry]
     Name=Autorandr Monitor Change
     Comment=run when monitor setup changes
     Exec=/bin/autorandr --detect
     Icon= /home/gregj/.local/share/pixmaps/laptop-monitor.png
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src
** Neo4j Desktop
   #+begin_src conf :tangle ~/.local/share/applications/neo4j-desktop.desktop
     [Desktop Entry]
     Name=Neo4j Desktop
     Comment=
     Exec=/usr/local/bin/neo4j-desktop
     Icon= /home/gregj/.local/share/pixmaps/neo4j-desktop.png
     Terminal=false
     Type=Application
     Categories=Database;
   #+end_src
** Polybar panel
   We can choose between simple and fancy
   #+begin_src conf :tangle ~/.local/share/applications/polybar-starter.desktop
     [Desktop Entry]
     Name=Polybar panel
     Comment=
     Exec=(killall polybar ; polybar --config=/home/gregj/.config/polybar/config-fancy floating -r -l info)
     Icon= /home/gregj/.local/share/pixmaps/ignition-sources-matches-icon.png
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src
** Protomolecule Virtualization - Proxmox or Harvester
   + Port 8006 for Proxmox, 30443 for Harvester
   #+begin_src conf :tangle ~/.local/share/applications/protomolecule.desktop
     [Desktop Entry]
     Name=Protomolecule
     Comment=Protomolecule HCI
     Exec=xdg-open https://protomolecule.magichome:30443
     Icon= /home/gregj/.local/share/pixmaps/protomolecule.png
     Terminal=false
     Type=Application
     Categories=Virtualization;HCI
   #+end_src

** Rancher Homelab
   #+begin_src conf :tangle no
         ~/.local/share/applications/rancher-homelab.desktop
         [Desktop Entry]
         Name=Rancher Homelab
         Comment=Rancher
         Exec=xdg-open https://rancher.172.16.17.116.nip.io/
         Icon=/home/gregj/.local/share/pixmaps/rancher-labs-icon.png
         Terminal=false
         Type=Application
         Categories=Kubernetes;Administration;Awesomeness
   #+end_src

** Rancher Public
   #+begin_src conf :tangle ~/.local/share/applications/rancher.desktop
     [Desktop Entry]
     Name=Rancher Public
     Comment=Rancher in TG AWS
     Exec=xdg-open https://rancher.hypecyclist.org/
     Icon=/home/gregj/.local/share/pixmaps/rancher-labs-icon.png
     Terminal=false
     Type=Application
     Categories=Kubernetes;Administration;Awesomeness
   #+end_src

** Reddit
   #+begin_src conf :tangle ~/.local/share/applications/freddit.desktop
     [Desktop Entry]
     Name=Reddit
     Comment=Reddit
     Exec=xdg-open https://reddit.com/
     Icon=/home/gregj/.local/share/pixmaps/reddit-monster.png
     Terminal=false
     Type=Application
     Categories=InstantMessaging;
   #+end_src
** Relaunch Albert
   #+begin_src conf :tangle ~/.local/share/applications/relaunch-albert.desktop
     [Desktop Entry]
     Name=Relaunch Albert
     Comment=Use Albert to relaunch Albert
     Exec= /home/gregj/bin/relaunch-albert.sh
     Icon= /home/gregj/.local/share/pixmaps/albert-einstein.jpg
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src
** Righty Tighty
   #+begin_src conf :tangle ~/.local/share/applications/righty.desktop
     [Desktop Entry]
     Name=Righty Tighty
     Comment=Set attached mouse or trackpad to right-handed use
     Exec=/home/gregj/bin/righty
     Icon= /home/gregj/.local/share/pixmaps/righthandcoords.gif
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src
** Rotate Wallpaper
   #+begin_src conf :tangle ~/.local/share/applications/rotate-wallpapers.desktop
     [Desktop Entry]
     Name=Rotate Wallpaper
     Comment=Yep
     Exec=/home/gregj/bin/rotate-wallpapers.sh
     Icon= /home/gregj/.local/share/pixmaps/rotate-wallpapers.jpg
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src
** Signal
   #+begin_src conf :tangle no
 ~/.local/share/applications/signal.desktop
     [Desktop Entry]
     Name=Signal
     Comment=Signal
     Exec=flatpak run org.signal.Signal
     Icon= /home/gregj/.local/share/pixmaps/signal-desktop.png
     Terminal=false
     Type=Application
     Categories=Messaging
   #+end_src
** Slack
   #+begin_src conf :tangle no
 ~/.local/share/applications/slack.desktop
     [Desktop Entry]
     Name=Slack
     Comment=Slack
     Exec=flatpak run com.slack.Slack
     Icon=/home/gregj/.local/share/pixmaps/slack.jpeg
     Terminal=false
     Type=Application
     Categories=InstantMessaging;
   #+end_src
** Solaar Logitech
   #+begin_src conf :tangle ~/.local/share/applications/Solaar.desktop
     [Desktop Entry]
     Name=Solaar Logitech
     Comment=Logitech Unifying software
     Exec=solaar
     Icon=/home/gregj/.local/share/pixmaps/solaar.svg
     Terminal=false
     Type=Application
     Categories=Utility
   #+end_src
** Spotify
   #+begin_src conf :tangle no
 ~/.local/share/applications/spotify.desktop
     [Desktop Entry]
     Name=Spotify
     Comment=Spotify
     Exec=flatpak run com.spotify.Client
     Icon= /home/gregj/.local/share/pixmaps/spotify-client.png
     Terminal=false
     Type=Application
     Categories=Music;Media
   #+end_src
** Spotify in browser
   #+begin_src conf :tangle no
     # ~/.local/share/applications/fspotify.desktop
     [Desktop Entry]
     Name=Spotify
     Comment=Spotify web player in Browser
     Exec=xdg-open https://open.spotify.com
     Icon=/home/gregj/.local/share/pixmaps/spotify-client.png
     Terminal=false
     Type=Application
     Categories=Music;Media
   #+end_src
** Steam games
*** Braid
*** Cuphead
    #+begin_src conf :tangle ~/.local/share/applications/steam-cuphead.desktop
      [Desktop Entry]
      Name=Cuphead
      Comment=Play this game on Steam
      Exec=steam steam://rungameid/268910
      Icon= /home/gregj/.local/share/pixmaps/cuphead.png
      Terminal=false
      Type=Application
      Categories=Game;
    #+end_src
*** Half-Life 2
*** Lovers in a Dangerous Spacetime
*** Moon Hunters
*** Overcooked! 2
    #+begin_src conf :tangle ~/.local/share/applications/steam-overcooked2.desktop
      [Desktop Entry]
      Name=Overcooked! 2
      Comment=Play this game on Steam
      Exec=steam steam://rungameid/728880
      Icon= /home/gregj/.local/share/pixmaps/overcooked2.png
      Terminal=false
      Type=Application
      Categories=Game;
    #+end_src
*** Portal 2
    #+begin_src conf :tangle ~/.local/share/applications/steam-portal2.desktop
      [Desktop Entry]
      Name=Portal 2
      Comment=Play this game on Steam
      Exec=steam steam://rungameid/620
      Icon= /home/gregj/.local/share/pixmaps/portal2.png
      Terminal=false
      Type=Application
      Categories=Game;
    #+end_src
*** Rocket League
    #+begin_src conf :tangle ~/.local/share/applications/steam-rocketleague.desktop
      [Desktop Entry]
      Name=Rocket League
      Comment=Play this game on Steam
      Exec=steam steam://rungameid/252950
      Icon= /home/gregj/.local/share/pixmaps/rocketleague.png
      Terminal=false
      Type=Application
      Categories=Game;
    #+end_src
*** Starbound
    #+begin_src conf :tangle ~/.local/share/applications/steam-starbound.desktop
      [Desktop Entry]
      Name=Starbound
      Comment=Play this game on Steam
      Exec=steam steam://rungameid/211820
      Icon= /home/gregj/.local/share/pixmaps/starbound.png
      Terminal=false
      Type=Application
      Categories=Game;
    #+end_src
*** Stardew Valley
    #+begin_src conf :tangle ~/.local/share/applications/steam-stardewvalley.desktop
      [Desktop Entry]
      Name=Stardew Valley
      Comment=Play this game on Steam
      Exec=steam steam://rungameid/413150
      Icon= /home/gregj/.local/share/pixmaps/stardew-valley.png
      Terminal=false
      Type=Application
      Categories=Game;
    #+end_src

** Suspend laptop
   #+begin_src conf :tangle ~/.local/share/applications/suspend-laptop.desktop
     [Desktop Entry]
     Name=Suspend / Sleep
     Comment=Sleepytime
     # Exec=/usr/bin/systemctl suspend
     Exec=systemctl suspend
     Icon= /home/gregj/.local/share/pixmaps/sleepy-stars.png
     Terminal=false
     Type=Application
     Categories=System
   #+end_src
** Switchy McSwitchface
   #+begin_src conf :tangle ~/.local/share/applications/switchy.desktop
     [Desktop Entry]
     Name=Switchy
     Comment=Netgear ProSafe Gigabit switch
     Exec=xdg-open http://switchy.magichome/
     Icon= /home/gregj/.local/share/pixmaps/netgear.jpeg
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src

** TigerGraph Documentation
   #+begin_src conf :tangle ~/.local/share/applications/tigergraph-documentation.desktop
     [Desktop Entry]
     Name=TigerGraph DOCUMENTATION
     Comment=Ohai
     Exec=xdg-open https://docs.tigergraph.com/v/3.2/admin/admin-guide/kubernetes
     Icon= /home/gregj/.local/share/pixmaps/tiger-freaky.png
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src

** TigerGraph GraphStudio
   #+begin_src conf :tangle ~/.local/share/applications/tigergraph-graphstudio.desktop
     [Desktop Entry]
     Name=Tigergraph GraphStudio
     Comment=
     Exec=xdg-open https://gs.hypecyclist.org:14240
     Icon= /home/gregj/.local/share/pixmaps/tigergraph-graphstudio-logo.png
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src

** TigerGraph Documentation
   #+begin_src conf :tangle ~/.local/share/applications/tigergraph-testdrives.desktop
     [Desktop Entry]
     Name=TigerGraph Test Drive Demo
     Comment=Test Drives for TigerGraph!
     Exec=xdg-open https://testdrive.tigergraph.com/
     Icon= /home/gregj/.local/share/pixmaps/tiger-freaky.png
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src
** Toggle Polybar Panel Show/Hide
   #+begin_src conf :tangle ~/.local/share/applications/toggle-polybar-panel-visibility.desktop
     [Desktop Entry]
     Name=Toggle Polybar Panel Show/Hide
     Comment=Polybar panel with system tray
     Exec=/home/gregj/bin/toggle-auto-hide-polybar.sh
     Icon= /home/gregj/.local/share/pixmaps/show-hide.png
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src
   #+begin_src bash :tangle ~/bin/toggle-auto-hide-polybar.sh
     pid=$(ps fax | grep hideIt | grep -v grep|head -1 | awk '{print $1}')
     echo "Debug: pid is |${pid}|"
     if [ -n "${pid}" ] ; then
         # it's active, so kill it, thus "pinning" our panel
         echo "killing ${pid}"
         ps fax | grep hideIt | grep -v grep | awk '{print $1}' | xargs kill
     else
         # it's not running so, start 'er up and autohide the panel
         # We first have to grab monitor 0 resolution to properly set regiob
         hregion=$(xrandr --listactivemonitors | egrep '^ *0:'  |cut -d':' -f2|cut -d' ' -f3 | sed 's,\([0-9]\+\)\/[0-9]\+x\([0-9]\+\).\+,0x\2+\1+-10,')
         setsid ~/.config/polybar/hideIt.sh --wait --region ${hregion} --name '^polybar-floating' > /dev/null 2>&1 &

     fi
   #+end_src
** Toggle XFCE4 Panel Show/Hide
   #+begin_src conf :tangle ~/.local/share/applications/toggle-xfce-panel-visibility.desktop
     [Desktop Entry]
     Name=Toggle XFCE4 Panel Show/Hide
     Comment=Panel with widgets for use with EXWM
     Exec=/home/gregj/bin/toggle-xfce4-panel-hide.sh
     Icon= /home/gregj/.local/share/pixmaps/xfce4-panel-icon-png-icon.jpg
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src
** Trello
   #+begin_src conf :tangle ~/.local/share/applications/trello.desktop
     [Desktop Entry]
     Name=Trello
     Comment=Um ... Trello!
     Exec=xdg-open https://trello.com/
     Icon=/home/gregj/.local/share/pixmaps/trello.png
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src
** Vterm
   Emacs vterm!
   #+begin_src conf :tangle ~/.local/share/applications/vterm.desktop
     [Desktop Entry]
     Name=Emacs Vterm
     Comment=Terminal
     Exec=/usr/local/bin/emacsclient -e '(vterm)'
     Icon= /home/gregj/.local/share/pixmaps/cool-terminal.jpeg
     Terminal=true
     Type=Application
     Categories=System;TerminalEmulator
   #+end_src
** XFCE4 Panel
   #+begin_src conf :tangle ~/.local/share/applications/exwm-xfce4-panel.desktop
     [Desktop Entry]
     Name=XFCE4 Panel
     Comment=Panel with widgets for use with EXWM
     # Exec=gnome-terminal -e "bash -c '/home/gregj/bin/xfce-panel-widgets.sh;/usr/bin/bash'"
     Exec=/home/gregj/bin/xfce-panel-widgets.sh
     Icon= /home/gregj/.local/share/pixmaps/xfce.png
     Terminal=false
     Type=Application
     Categories=Office;Productivity;
   #+end_src
** YouTube
   #+begin_src conf :tangle ~/.local/share/applications/youtube.desktop
     [Desktop Entry]
     Name=YouTube
     Comment=
     Exec=xdg-open https://youtube.com
     Icon= /home/gregj/.local/share/pixmaps/youtube-kids-new-logo.png
     Terminal=false
     Type=Application
     Categories=Chat;Community
   #+end_src

** Yummy Sauce - mealie
   #+begin_src conf :tangle ~/.local/share/applications/yummysauce.desktop
     [Desktop Entry]
     Name=Yummy Sauce Recipes
     Comment=
     Exec=xdg-open http://172.16.17.5:9925/
     Icon= /home/gregj/.local/share/pixmaps/mealie-favicon.png
     Terminal=false
     Type=Application
     Categories=Cooking;Recipes
   #+end_src

** Zoom
   Use this if you are not using the OS package manager installation - set =:tangle no= if
   you are
   #+begin_src conf :tangle no
 ~/.local/share/applications/zoom.desktop
     [Desktop Entry]
     Encoding=UTF-8
     Name=Zoom
     GenericName=Zoom
     Comment=Zoom it up
     Exec=flatpak run us.zoom.Zoom
     Icon= /home/gregj/.local/share/pixmaps/google-cloud-logo.png
     Terminal=false
     Type=Application
     Categories=Application;Network;Productivity;
     StartupNotify=True
   #+end_src
