(deftheme gjg-twilight
  "Created 2013-11-04.")

(custom-theme-set-faces
 'gjg-twilight
 ;; '(default ((t (:background "#181a26" :foreground "#f8f8f8")))) ;; original twilight default
 '(default ((t (:background "#181a26" :foreground "gray80")))) ;; original twilight default
 ;; '(default ((t (:family "Source Code Pro" :foundry "outline" :width normal :height 102 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "gray80" :background "#181a26" :stipple nil :inherit nil))))
 '(highlight ((t (:background "MidnightBlue"))))
 '(hl-line ((t (:background "MidnightBlue"))))
 '(cursor ((t (:foreground "#a7a7a7" :background "green"))))
 '(region ((t (:background "#103050"))))
 '(blue ((t (:foreground "blue"))))
 '(border-glyph ((t (nil))))
 '(buffers-tab ((t (:background "#141414" :foreground "#CACACA"))))
 '(font-lock-builtin-face ((t (:foreground "LightCoral"))))
 '(font-lock-comment-face ((t (:foreground "#7f7f7f")))) ;; gray50
 '(font-lock-constant-face ((t (:foreground "DarkOliveGreen3"))))
 '(font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
 '(font-lock-function-name-face ((t (:foreground "goldenrod"))))
 '(font-lock-keyword-face ((t (:foreground "DeepSkyBlue1"))))
 '(font-lock-preprocessor-face ((t (:foreground "gold" :inherit (font-lock-builtin-face)))))
 '(font-lock-reference-face ((t (:foreground "SlateBlue"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#E9C062" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "red" :inherit (bold)))))
 '(minibuffer-prompt ((t (:foreground "CadetBlue1"))))
 '(ido-subdir ((t (:foreground "#CF6A4C"))))
 '(ido-first-match ((t (:foreground "#8F9D6A"))))
 '(ido-only-match ((t (:foreground "#8F9D6A"))))
 '(mumamo-background-chunk-submode ((t (:background "#222222")))) 
 '(font-lock-string-face ((t (:foreground "burlywood"))))
 '(font-lock-type-face ((t (:foreground "CadetBlue1"))))
 '(font-lock-variable-name-face ((t (:foreground "SeaGreen2"))))
 '(font-lock-warning-face ((t (:foreground "red" :background "#EE799F" :inherit (error)))))
 '(gui-element ((t (:background "#D4D0C8" :foreground "black"))))
 '(highline-face ((t (:background "SeaGreen"))))
 '(left-margin ((t (nil))))
 '(text-cursor ((t (:background "yellow" :foreground "black"))))
 '(toolbar ((t (nil))))
 '(underline ((nil (:underline nil))))
 '(zmacs-region ((t (:background "snow" :foreground "blue"))))
 ;; '(mode-line ((t (:box (:line-width 1 :color nil :style released-button) :foreground "black" :background "gray75"))))
 ;; '(fixed-pitch ((t (:family "Monospace"))))
 ;; '(variable-pitch ((t (:family "Sans Serif"))))
 ;; '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 ;; '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 ;; '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 ;; '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 ;; '(font-lock-comment-delimiter-face ((t (:foreground "gray50" :inherit (font-lock-comment-face)))))
 ;; '(font-lock-doc-face ((t (:foreground "moccasin" :inherit (font-lock-string-face)))))
 ;; '(font-lock-negation-char-face ((t nil)))
 ;; '(button ((t (:inherit (link)))))
 ;; '(link ((((class color) (min-colors 88) (background light)) (:underline t :foreground "RoyalBlue3")) (((class color) (background light)) (:underline t :foreground "blue")) (((class color) (min-colors 88) (background dark)) (:underline t :foreground "cyan1")) (((class color) (background dark)) (:underline t :foreground "cyan")) (t (:inherit (underline)))))
 ;; '(link-visited ((t (:foreground "violet" :inherit (link)))))
 ;; '(fringe ((t (:background "black"))))
 ;; '(header-line ((t (:box nil :foreground "grey90" :background "grey20" :inherit (mode-line)))))
 ;; '(tooltip ((t (:foreground "systeminfotext" :background "systeminfowindow" :inherit (variable-pitch)))))
 ;; '(mode-line-buffer-id ((t (:weight bold :foreground "blue4"))))
 ;; '(mode-line-emphasis ((t (:weight bold))))
 ;; '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 ;; '(mode-line-inactive ((t (:weight light :box (:line-width 1 :color "gray40" :style nil) :foreground "black" :background "gray40" :inherit (mode-line)))))
 ;; '(isearch ((t (:foreground "white" :background "coral2"))))
 ;; '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 ;; '(lazy-highlight ((t (:foreground "white" :background "cadetblue"))))
 ;; '(match ((t (:background "DeepPink4"))))
 ;; '(next-error ((t (:inherit (region)))))
 '(show-paren-match ((t (:weight bold :foreground "cyan" :background "#292929"))))
 '(show-paren-mismatch ((t (:weight bold :foreground "red" :background "#5f5f5f"))))
 '(query-replace ((t (:inherit (isearch)))))
 '(outline-1 ((t (:inherit nil :foreground "#ffbb66" :weight bold))))
 '(outline-2 ((t (:inherit nil :foreground "#aaee77" :weight bold))))
 '(outline-3 ((t (:inherit nil :foreground "#88ccee" :weight bold))))
 '(outline-4 ((t (:inherit nil :foreground "#ee88ff" :weight bold))))
 '(outline-5 ((t (:inherit nil :foreground "#ffbb66" :weight bold))))
 '(org-level-1 ((t (:inherit outline-1))))
 '(org-level-2 ((t (:inherit outline-2))))
 '(org-level-3 ((t (:inherit outline-3))))
 '(org-level-4 ((t (:inherit outline-4)))))

(provide-theme 'gjg-twilight)
